---
- hosts: all
  become: true
  ignore_errors: yes
  tasks:
  - name: (pre_event) Free space in /boot partition is greater than 40MB
#    shell: df -P /boot | grep -e /dev/xvda1 | tr -s ' ' | cut -d ' ' -f 4
    shell: i=$(df -P /boot|grep -i /dev|awk '{print $1}');df -P /boot  | grep -e $i  | tr -s ' ' | cut -d ' ' -f 4
    register: boot_partition_space

  - name: Remove old Kernel if space less than 40MB
    shell:
     cmd: /usr/bin/yum install -y yum-utils ; /usr/bin/package-cleanup --oldkernels --count=1 -y
     warn: false
    when: boot_partition_space.stdout|int <=40000 and (ansible_distribution == "RedHat" or ansible_distribution == "CentOS")

  - name: Checking the /boot space after package-cleanup utility
#    shell: df -P /boot | grep -e /dev/xvda1 | tr -s ' ' | cut -d ' ' -f 4
    shell: i=$(df -P /boot|grep -i /dev|awk '{print $1}');df -P /boot  | grep -e $i  | tr -s ' ' | cut -d ' ' -f 4
    register: New_boot_partition_space

  - name: Need manual clean up for /boot
    debug: msg="Need manual intervension to clean up /boot {{ansible_hostname}} {{ansible_default_ipv4.address}}. Free space is {{New_boot_partition_space.stdout|int/1024}}MB"
    when: New_boot_partition_space.stdout|int <=40000

  - name: No need manaul clean up for /boot
    debug: msg="No need manual intervension to clean up /boot {{ansible_hostname}} {{ansible_default_ipv4.address}}. /boot looks good {{New_boot_partition_space.stdout|int/1024}}MB"
    when: New_boot_partition_space.stdout|int >=40000

  - name: (pre_event) Free space in /var before update
#    shell: i=$(mount |grep -i /var|grep -v /var/ |awk '{print $1}');df -P /var  | grep -e $i  | tr -s ' ' | cut -d ' ' -f 4
    shell: i=$(df -P /var|grep -i /dev|awk '{print $1}');df -P /var  | grep -e $i  | tr -s ' ' | cut -d ' ' -f 4
    register: var_space

  - name: Remove space if less than  750MB
    when: var_space.stdout|int <= 750000
    script: var.sh

  - name: Checking the /var space after clean up by script
#    shell: i=$(mount |grep -i /var|grep -v /var/ |awk '{print $1}');df -P /var  | grep -e $i  | tr -s ' ' | cut -d ' ' -f 4
    shell: i=$(df -P /var|grep -i /dev|awk '{print $1}');df -P /var  | grep -e $i  | tr -s ' ' | cut -d ' ' -f 4
    register: New_var_space

  - name: Need manual clean up for /var
    debug: msg="Need manual intervension to clean up /var {{ansible_hostname}} {{ansible_default_ipv4.address}}. Free space is {{New_var_space.stdout|int/1024}}MB"
    when: New_var_space.stdout|int <=750000

  - name: No need manaul clean up for /var
    debug: msg="No need manual intervension to clean up /var {{ansible_hostname}} {{ansible_default_ipv4.address}}. /var looks good {{New_var_space.stdout|int/1024}}MB"
    when: New_var_space.stdout|int >=750000

  - name: (pre_event) Free space in /var/log before update
#    shell: i=$(mount |grep -i /var/log|grep -v /var/log |awk '{print $1}'); df -P /var/log | grep -e $i  | tr -s ' ' | cut -d ' ' -f 4
    shell: i=$(df -P /var/log|grep -i /dev|awk '{print $1}');df -P /var/log  | grep -e $i  | tr -s ' ' | cut -d ' ' -f 4
    register: varlog_space

  - name: Need manual clean up for /var/log
    debug: msg="Need manual intervension to clean up /var/log {{ansible_hostname}} {{ansible_default_ipv4.address}}. Free space is {{varlog_space.stdout|int/1024}}MB"
    when: varlog_space.stdout|int <=500000

  - name: No need manaul clean up for /var/log
    debug: msg="No need manual intervension to clean up /var/log {{ansible_hostname}} {{ansible_default_ipv4.address}}. /var/log looks good {{varlog_space.stdout|int/1024}}MB"
    when: varlog_space.stdout|int >=500000

  - name: Remove audit logs, if space less than 75 percentage.
    script: audit_clean_critical.sh

