---
# tasks file for kernelcheck_reboot

   - name: 'kernel version from facts'
     debug:
      msg: "Running Kernel is {{Running_Kernel}}"

   - name: Get latest installed kernel
     shell: rpm -q --last kernel | perl -pe 's/^kernel-(\S+).*/$1/' | head -1
     args:
      warn: false
     register: instal_ker

   - name: Show the last installed kernel
     debug:
      msg: "Last installed kernel is {{instal_ker.stdout}}"

   - name: Reboot required, when running kernel not equal lastest installed kernel
     debug:
      msg: " Reboot required as the running kernel not equal to installed kernel"
     when: Running_Kernel != instal_ker.stdout

   - name: Reboot not required, when running kernel equal lastest installed kernel
     debug:
      msg: " Reboot not required as the running kernel equal to installed kernel"
     when: Running_Kernel == instal_ker.stdout

   - name: Reboot and add eagerfpu in kernel parameter
     shell:
      cmd: /sbin/grubby --update-kernel=ALL --args=eagerfpu=off

   - name: Rebooting host(s).
     shell: sleep 2 && /sbin/shutdown -r now "Reboot required for updated kernel." && sleep 2
     async: 60
     poll: 0
     when: Running_Kernel != instal_ker.stdout

   - name: Waiting for host(s) to reboot
     wait_for_connection:
      delay: 180
      timeout: 300
     when: Running_Kernel != instal_ker.stdout
...
